//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.11 at 01:44:32 PM IST 
//

package com.poc.loans.bbgtrades.xml.request;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="cancellationComment" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="cancellationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="cancellationReasonCode" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="circleId" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "CancelTrade")
public class CancelTrade {

	@XmlAttribute(name = "cancellationComment", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String cancellationComment;
	@XmlAttribute(name = "cancellationDate", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String cancellationDate;
	@XmlAttribute(name = "cancellationReasonCode", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String cancellationReasonCode;
	@XmlAttribute(name = "circleId", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String circleId;
	@XmlAttribute(name = "version", required = true)
	protected String version;

	/**
	 * Gets the value of the cancellationComment property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCancellationComment() {
		return cancellationComment;
	}

	/**
	 * Sets the value of the cancellationComment property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCancellationComment(String value) {
		this.cancellationComment = value;
	}

	/**
	 * Gets the value of the cancellationDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCancellationDate() {
		return cancellationDate;
	}

	/**
	 * Sets the value of the cancellationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCancellationDate(String value) {
		this.cancellationDate = value;
	}

	/**
	 * Gets the value of the cancellationReasonCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCancellationReasonCode() {
		return cancellationReasonCode;
	}

	/**
	 * Sets the value of the cancellationReasonCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCancellationReasonCode(String value) {
		this.cancellationReasonCode = value;
	}

	/**
	 * Gets the value of the circleId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCircleId() {
		return circleId;
	}

	/**
	 * Sets the value of the circleId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCircleId(String value) {
		this.circleId = value;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setVersion(String value) {
		this.version = value;
	}

}
