//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.23 at 06:15:50 PM IST 
//


package com.poc.loans.bbgtrades.xml.request;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Counterparty"/>
 *         &lt;element ref="{}FacilityPosition"/>
 *       &lt;/sequence>
 *       &lt;attribute name="branchCode" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="buySellCode" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="circleFinalStatusCode" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="dealInternalId" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="eventComment" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="expectedCloseDate" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="interestFeeSettlement" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="investmentType" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="isDistressed" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="pricingComment" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="riskBook" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="settleNet" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="tradeDate" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="trader" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "counterparty",
    "facilityPosition",
    "misCode"
})
@XmlRootElement(name = "CreateTrade")
public class CreateTrade {
	
    @XmlElement(name = "Counterparty", required = true, type = Counterparty.class)
    protected Counterparty counterparty;
    @XmlElement(name = "FacilityPosition", required = true, type = FacilityPosition.class)
    protected FacilityPosition facilityPosition;
/*    @XmlElement(name = "MISCode", required = true, type = MISCode.class)
    protected MISCode mISCode;*/
    @XmlElement(name = "MISCode", required = true, type = MISCode.class)
    protected List<MISCode> misCode;
    @XmlAttribute(name = "branchCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String branchCode;
    @XmlAttribute(name = "buySellCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String buySellCode;
    @XmlAttribute(name = "circleFinalStatusCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String circleFinalStatusCode;
    @XmlAttribute(name = "dealInternalId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String dealInternalId;
    @XmlAttribute(name = "eventComment", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String eventComment;
    @XmlAttribute(name = "expectedCloseDate", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String expectedCloseDate;
    @XmlAttribute(name = "interestFeeSettlement", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String interestFeeSettlement;
    @XmlAttribute(name = "investmentType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String investmentType;
    @XmlAttribute(name = "isDistressed", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String isDistressed;
    @XmlAttribute(name = "pricingComment", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pricingComment;
    @XmlAttribute(name = "riskBook", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String riskBook;
    @XmlAttribute(name = "settleNet", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String settleNet;
    @XmlAttribute(name = "tradeDate", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tradeDate;
    @XmlAttribute(name = "trader", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String trader;
    @XmlAttribute(name = "version", required = true)
    protected String version;


	/**
     * Gets the value of the counterparty property.
     * 
     * @return
     *     possible object is
     *     {@link Counterparty }
     *     
     */
    public Counterparty getCounterparty() {
        return counterparty;
    }

    /**
     * Sets the value of the counterparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Counterparty }
     *     
     */
    public void setCounterparty(Counterparty value) {
        this.counterparty = value;
    }

    /**
     * Gets the value of the facilityPosition property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityPosition }
     *     
     */
    public FacilityPosition getFacilityPosition() {
        return facilityPosition;
    }

    /**
     * Sets the value of the facilityPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityPosition }
     *     
     */
    public void setFacilityPosition(FacilityPosition value) {
        this.facilityPosition = value;
    }

    /**
     * Gets the value of the branchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchCode(String value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the buySellCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuySellCode() {
        return buySellCode;
    }

    /**
     * Sets the value of the buySellCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuySellCode(String value) {
        this.buySellCode = value;
    }

    /**
     * Gets the value of the circleFinalStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCircleFinalStatusCode() {
        return circleFinalStatusCode;
    }

    /**
     * Sets the value of the circleFinalStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCircleFinalStatusCode(String value) {
        this.circleFinalStatusCode = value;
    }

    /**
     * Gets the value of the dealInternalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealInternalId() {
        return dealInternalId;
    }

    /**
     * Sets the value of the dealInternalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealInternalId(String value) {
        this.dealInternalId = value;
    }

    /**
     * Gets the value of the eventComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventComment() {
        return eventComment;
    }

    /**
     * Sets the value of the eventComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventComment(String value) {
        this.eventComment = value;
    }

    /**
     * Gets the value of the expectedCloseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpectedCloseDate() {
        return expectedCloseDate;
    }

    /**
     * Sets the value of the expectedCloseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpectedCloseDate(String value) {
        this.expectedCloseDate = value;
    }

    /**
     * Gets the value of the interestFeeSettlement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestFeeSettlement() {
        return interestFeeSettlement;
    }

    /**
     * Sets the value of the interestFeeSettlement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestFeeSettlement(String value) {
        this.interestFeeSettlement = value;
    }

    /**
     * Gets the value of the investmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvestmentType() {
        return investmentType;
    }

    /**
     * Sets the value of the investmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvestmentType(String value) {
        this.investmentType = value;
    }

    /**
     * Gets the value of the isDistressed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDistressed() {
        return isDistressed;
    }

    /**
     * Sets the value of the isDistressed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDistressed(String value) {
        this.isDistressed = value;
    }

    /**
     * Gets the value of the pricingComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingComment() {
        return pricingComment;
    }

    /**
     * Sets the value of the pricingComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingComment(String value) {
        this.pricingComment = value;
    }

    /**
     * Gets the value of the riskBook property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiskBook() {
        return riskBook;
    }

    /**
     * Sets the value of the riskBook property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiskBook(String value) {
        this.riskBook = value;
    }

    /**
     * Gets the value of the settleNet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettleNet() {
        return settleNet;
    }

    /**
     * Sets the value of the settleNet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettleNet(String value) {
        this.settleNet = value;
    }

    /**
     * Gets the value of the tradeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * Sets the value of the tradeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeDate(String value) {
        this.tradeDate = value;
    }

    /**
     * Gets the value of the trader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrader() {
        return trader;
    }

    /**
     * Sets the value of the trader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrader(String value) {
        this.trader = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

	/**
	 * @return the mISCode
	 */
/*	public MISCode getmISCode() {
		return mISCode;
	}*/
	
    public List<MISCode> getMISCode() {
        if (misCode == null) {
            misCode = new ArrayList<MISCode>();
        }
        return this.misCode;
    }

	/**
	 * @param mISCode the mISCode to set
	 */
	public void setmISCode(List<MISCode> misCode) {
		if (null == misCode) {
			this.misCode = new ArrayList<MISCode>();
		}
		this.misCode = misCode;
	}

	/**
	 * @return the trade
	 */

}
