//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.01 at 04:32:09 PM IST 
//


package com.poc.loans.bbgtrades.xml.request;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ServicingGroup"/>
 *         &lt;element ref="{}Risk"/>
 *         &lt;element ref="{}LoanPurpose"/>
 *         &lt;element ref="{}MISCode"/>
 *         &lt;element ref="{}FeePricing"/>
 *         &lt;element ref="{}FacilityInterestPricing"/>
 *       &lt;/sequence>
 *       &lt;attribute name="agreementDate" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="currency" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="dealTrackingNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="effectiveDate" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="expiryDate" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="facilityName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="facilityType" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="finalMaturityDate" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="proposedCommitmentAmount" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "servicingGroup",
    "risk",
    "loanPurpose",
    "misCode",
    "feePricing",
    "facilityInterestPricing"
})
@XmlRootElement(name = "CreateFacility")
public class CreateFacility {

    @XmlElement(name = "ServicingGroup", required = true)
    protected ServicingGroup servicingGroup;
    @XmlElement(name = "Risk", required = true)
    protected Risk risk;
    @XmlElement(name = "LoanPurpose", required = true)
    protected LoanPurpose loanPurpose;
    @XmlElement(name = "MISCode", required = true)
    protected MISCode misCode;
    @XmlElement(name = "FeePricing", required = true)
    protected FeePricing feePricing;
    @XmlElement(name = "FacilityInterestPricing", required = true)
    protected FacilityInterestPricing facilityInterestPricing;
    @XmlAttribute(name = "agreementDate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String agreementDate;
    @XmlAttribute(name = "currency", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String currency;
    @XmlAttribute(name = "dealTrackingNumber", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String dealTrackingNumber;
    @XmlAttribute(name = "effectiveDate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String effectiveDate;
    @XmlAttribute(name = "expiryDate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String expiryDate;
    @XmlAttribute(name = "facilityName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String facilityName;
    @XmlAttribute(name = "facilityType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String facilityType;
    @XmlAttribute(name = "finalMaturityDate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String finalMaturityDate;
    @XmlAttribute(name = "proposedCommitmentAmount", required = true)
    protected String proposedCommitmentAmount;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the servicingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link ServicingGroup }
     *     
     */
    public ServicingGroup getServicingGroup() {
        return servicingGroup;
    }

    /**
     * Sets the value of the servicingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicingGroup }
     *     
     */
    public void setServicingGroup(ServicingGroup value) {
        this.servicingGroup = value;
    }

    /**
     * Gets the value of the risk property.
     * 
     * @return
     *     possible object is
     *     {@link Risk }
     *     
     */
    public Risk getRisk() {
        return risk;
    }

    /**
     * Sets the value of the risk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Risk }
     *     
     */
    public void setRisk(Risk value) {
        this.risk = value;
    }

    /**
     * Gets the value of the loanPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link LoanPurpose }
     *     
     */
    public LoanPurpose getLoanPurpose() {
        return loanPurpose;
    }

    /**
     * Sets the value of the loanPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanPurpose }
     *     
     */
    public void setLoanPurpose(LoanPurpose value) {
        this.loanPurpose = value;
    }

    /**
     * Gets the value of the misCode property.
     * 
     * @return
     *     possible object is
     *     {@link MISCode }
     *     
     */
    public MISCode getMISCode() {
        return misCode;
    }

    /**
     * Sets the value of the misCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISCode }
     *     
     */
    public void setMISCode(MISCode value) {
        this.misCode = value;
    }

    /**
     * Gets the value of the feePricing property.
     * 
     * @return
     *     possible object is
     *     {@link FeePricing }
     *     
     */
    public FeePricing getFeePricing() {
        return feePricing;
    }

    /**
     * Sets the value of the feePricing property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeePricing }
     *     
     */
    public void setFeePricing(FeePricing value) {
        this.feePricing = value;
    }

    /**
     * Gets the value of the facilityInterestPricing property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityInterestPricing }
     *     
     */
    public FacilityInterestPricing getFacilityInterestPricing() {
        return facilityInterestPricing;
    }

    /**
     * Sets the value of the facilityInterestPricing property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityInterestPricing }
     *     
     */
    public void setFacilityInterestPricing(FacilityInterestPricing value) {
        this.facilityInterestPricing = value;
    }

    /**
     * Gets the value of the agreementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementDate() {
        return agreementDate;
    }

    /**
     * Sets the value of the agreementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementDate(String value) {
        this.agreementDate = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the dealTrackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealTrackingNumber() {
        return dealTrackingNumber;
    }

    /**
     * Sets the value of the dealTrackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealTrackingNumber(String value) {
        this.dealTrackingNumber = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDate(String value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the facilityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityName() {
        return facilityName;
    }

    /**
     * Sets the value of the facilityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityName(String value) {
        this.facilityName = value;
    }

    /**
     * Gets the value of the facilityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityType() {
        return facilityType;
    }

    /**
     * Sets the value of the facilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityType(String value) {
        this.facilityType = value;
    }

    /**
     * Gets the value of the finalMaturityDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalMaturityDate() {
        return finalMaturityDate;
    }

    /**
     * Sets the value of the finalMaturityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalMaturityDate(String value) {
        this.finalMaturityDate = value;
    }

    /**
     * Gets the value of the proposedCommitmentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getProposedCommitmentAmount() {
        return proposedCommitmentAmount;
    }

    /**
     * Sets the value of the proposedCommitmentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProposedCommitmentAmount(String value) {
        this.proposedCommitmentAmount = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
