//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.01 at 04:36:16 PM IST 
//


package com.poc.loans.bbgtrades.xml.request;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DealBorrowerServicingGroup"/>
 *       &lt;/sequence>
 *       &lt;attribute name="customerExternalId" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dealBorrowerServicingGroup"
})
@XmlRootElement(name = "DealBorrower")
public class DealBorrower {

    @XmlElement(name = "DealBorrowerServicingGroup", required = true)
    protected DealBorrowerServicingGroup dealBorrowerServicingGroup;
    @XmlAttribute(name = "customerExternalId", required = true)
    protected String customerExternalId;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the dealBorrowerServicingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link DealBorrowerServicingGroup }
     *     
     */
    public DealBorrowerServicingGroup getDealBorrowerServicingGroup() {
        return dealBorrowerServicingGroup;
    }

    /**
     * Sets the value of the dealBorrowerServicingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link DealBorrowerServicingGroup }
     *     
     */
    public void setDealBorrowerServicingGroup(DealBorrowerServicingGroup value) {
        this.dealBorrowerServicingGroup = value;
    }

    /**
     * Gets the value of the customerExternalId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getCustomerExternalId() {
        return customerExternalId;
    }

    /**
     * Sets the value of the customerExternalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerExternalId(String value) {
        this.customerExternalId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
